### PR TITLE
Extend tests for o2r-transporter

### PR DESCRIPTION
**Pull request by Timmimim**
Add tests for job file download and `.csv` truncation (a.o.).

### CODE REVIEW

**Comment by nuest** [comment]
@Timmimim The problem "Uncaught TypeError: Cannot read property 'o2r' of undefined" might come from the publishment not succeeding in time (since now a lot more happens on the server side). Try increasing the waiting period in the test code.

**Comment by Timmimim** [comment]
Will do!
I noted some other issues as well, that stem from my running the file download tests only. Adding that `.csv` file messed up a number of tests, which I am currently patching up.

**Comment by nuest** [comment]
Yes, on that: Please create a _new_ ERC with this additional data, do not extend ` test/erc/with_metadata`.

**Comment by nuest** [comment]
Tests work fine locally, issue is with the access rights of the second level container `o2r-meta` when run on Travis, where the user `o2r` (which exists in the container) does not exist.

**Pull request merged**
